### ISSUE TITLE
Installing trouble on Ubuntu Hardy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hubnerp/kbang#40]
```
I had new to Kbang, and I hope this is the right way to found solution to
my problem.
I had downloaded the source code by svn (first, and from the .tar.bz2 pack
after, 0.1.3) of kbang, I think it's the 123rev.
So, using the istrucion on manual I had compiled the source whit qt4, but
in every case I receive this error:

src/server/player.cpp
src/server/player.cpp: In member function ‘bool
Player::removeCardFromHand(PlayingCard*)’:
src/server/player.cpp:194: error: ‘class QList<PlayingCard*>’ has no member
named ‘removeOne’
src/server/player.cpp: In member function ‘bool
Player::removeCardFromTable(PlayingCard*)’:
src/server/player.cpp:206: error: ‘class QList<PlayingCard*>’ has no member
named ‘removeOne’
src/server/player.cpp: In member function ‘bool
Player::removeCardFromSelection(PlayingCard*)’:
src/server/player.cpp:211: error: ‘class QList<PlayingCard*>’ has no member
named ‘removeOne’
make[1]: *** [obj/server/player.o] Error 1
make[1]: Leaving directory `/home/piero/Documenti/BANG/soft/kbang-0.1.3-src'
make: *** [sub-kbang_server-pro-make_default-ordered] Error 2


I'm working on Ubuntu Hardy  whit  2.6.24-24-generic kernel...
Thank's for any solution
```

Original issue reported on code.google.com by `piero.da...@gmail.com` on 7 Jul 2009 at 3:59
